config/routes.rb
Rails.application.routes.draw do
  resources :tracks
  resources :duos
  root 'home#index'
  resources :handlers
  get 'home/index'
  resources :dogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/models/duo.rb
class Duo < ApplicationRecord
  belongs_to :handler
  belongs_to :dog
end

app/models/handler.rb
class Handler < ApplicationRecord
end

app/models/track.rb
class Track < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :breed, :number)
    end
end

app/controllers/duos_controller.rb
class DuosController < ApplicationController
  before_action :set_duo, only: [:show, :edit, :update, :destroy]

  #Create Dogs all
  @dogs = Dog.all
  # GET /duos
  # GET /duos.json
  def index
    @duos = Duo.all
  end

  # GET /duos/1
  # GET /duos/1.json
  def show
  end

  # GET /duos/new
  def new
    @duo = Duo.new
  end

  # GET /duos/1/edit
  def edit
  end

  # POST /duos
  # POST /duos.json
  def create
    @duo = Duo.new(duo_params)

    respond_to do |format|
      if @duo.save
        format.html { redirect_to @duo, notice: 'Duo was successfully created.' }
        format.json { render :show, status: :created, location: @duo }
      else
        format.html { render :new }
        format.json { render json: @duo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /duos/1
  # PATCH/PUT /duos/1.json
  def update
    respond_to do |format|
      if @duo.update(duo_params)
        format.html { redirect_to @duo, notice: 'Duo was successfully updated.' }
        format.json { render :show, status: :ok, location: @duo }
      else
        format.html { render :edit }
        format.json { render json: @duo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /duos/1
  # DELETE /duos/1.json
  def destroy
    @duo.destroy
    respond_to do |format|
      format.html { redirect_to duos_url, notice: 'Duo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_duo
      @duo = Duo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def duo_params
      params.require(:duo).permit(:handler_id, :dog_id)
    end
end

app/controllers/handlers_controller.rb
class HandlersController < ApplicationController
  before_action :set_handler, only: [:show, :edit, :update, :destroy]

  # GET /handlers
  # GET /handlers.json
  def index
    @handlers = Handler.all
  end

  # GET /handlers/1
  # GET /handlers/1.json
  def show
  end

  # GET /handlers/new
  def new
    @handler = Handler.new
  end

  # GET /handlers/1/edit
  def edit
  end

  # POST /handlers
  # POST /handlers.json
  def create
    @handler = Handler.new(handler_params)

    respond_to do |format|
      if @handler.save
        format.html { redirect_to @handler, notice: 'Handler was successfully created.' }
        format.json { render :show, status: :created, location: @handler }
      else
        format.html { render :new }
        format.json { render json: @handler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /handlers/1
  # PATCH/PUT /handlers/1.json
  def update
    respond_to do |format|
      if @handler.update(handler_params)
        format.html { redirect_to @handler, notice: 'Handler was successfully updated.' }
        format.json { render :show, status: :ok, location: @handler }
      else
        format.html { render :edit }
        format.json { render json: @handler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /handlers/1
  # DELETE /handlers/1.json
  def destroy
    @handler.destroy
    respond_to do |format|
      format.html { redirect_to handlers_url, notice: 'Handler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_handler
      @handler = Handler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def handler_params
      params.require(:handler).permit(:name, :country, :number)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:truck_mode, :judge, :time, :speed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/duos_helper.rb
module DuosHelper
end

app/helpers/handlers_helper.rb
module HandlersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/dogs/_form.html.erb
<%= form_with(model: dog, local: true) do |form| %>
  <% if dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :breed %>
    <%= form.text_field :breed %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Breed</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%= dog.breed %></td>
        <td><%= dog.number %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dog', new_dog_path %>
<%= link_to "Home", root_path %>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @dog.breed %>
</p>

<p>
  <strong>Number:</strong>
  <%= @dog.number %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/duos/_form.html.erb
<%= form_with(model: duo, local: true) do |form| %>
  <% if duo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(duo.errors.count, "error") %> prohibited this duo from being saved:</h2>

      <ul>
      <% duo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :handler_id %>
    <%= form.text_field :handler_id %>
  </div>

  <div class="field">
    <%= form.label :dog_id %>
    <%= form.text_field :dog_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/duos/edit.html.erb
<h1>Editing Duo</h1>
    <% @dogs = Dog.all %>
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Breed</th>
      <th>Number</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.id %></td>
        <td><%= dog.name %></td>
        <td><%= dog.breed %></td>
        <td><%= dog.number %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'form', duo: @duo %>

<%= link_to 'Show', @duo %> |
<%= link_to 'Back', duos_path %>

app/views/duos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Duos</h1>

<table>
  <thead>
    <tr>
      <th>Handler</th>
      <th>Dog</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @duos = Duo.all %>
    <% @duos.each do |duo| %>
      <tr>
        <td><%= duo.handler.name.to_s %></td>
        <td><%= duo.dog.name.to_s %></td>
        <td><%= link_to 'Show', duo %></td>
        <td><%= link_to 'Edit', edit_duo_path(duo) %></td>
        <td><%= link_to 'Destroy', duo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Duo', new_duo_path %>
<%= link_to "Home", root_path %>

app/views/duos/new.html.erb
<h1>New Duo</h1>

<%= render 'form', duo: @duo %>

<%= link_to 'Back', duos_path %>

app/views/duos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Handler:</strong>
  <%= @duo.handler.name.to_s %>
</p>

<p>
  <strong>Dog:</strong>
  <%= @duo.dog.name.to_s %>
</p>

<%= link_to 'Edit', edit_duo_path(@duo) %> |
<%= link_to 'Back', duos_path %>

app/views/handlers/_form.html.erb
<%= form_with(model: handler, local: true) do |form| %>
  <% if handler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(handler.errors.count, "error") %> prohibited this handler from being saved:</h2>

      <ul>
      <% handler.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/handlers/edit.html.erb
<h1>Editing Handler</h1>

<%= render 'form', handler: @handler %>

<%= link_to 'Show', @handler %> |
<%= link_to 'Back', handlers_path %>

app/views/handlers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Handlers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @handlers.each do |handler| %>
      <tr>
        <td><%= handler.name %></td>
        <td><%= handler.country %></td>
        <td><%= handler.number %></td>
        <td><%= link_to 'Show', handler %></td>
        <td><%= link_to 'Edit', edit_handler_path(handler) %></td>
        <td><%= link_to 'Destroy', handler, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Handler', new_handler_path %>
<%= link_to "Home", root_path %>

app/views/handlers/new.html.erb
<h1>New Handler</h1>

<%= render 'form', handler: @handler %>

<%= link_to 'Back', handlers_path %>

app/views/handlers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @handler.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @handler.country %>
</p>

<p>
  <strong>Number:</strong>
  <%= @handler.number %>
</p>

<%= link_to 'Edit', edit_handler_path(@handler) %> |
<%= link_to 'Back', handlers_path %>

app/views/home/index.html.erb
<h1>Agility App!</h1>
<%= link_to "Dogs", dogs_path %>
<%= link_to "Handlers", handlers_path %>
<%= link_to "Duos", duos_path %>
<%= link_to "Tracks", tracks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Www</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tracks/_form.html.erb
<%= form_with(model: track, local: true) do |form| %>
  <% if track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :truck_mode %>
    <%= form.text_field :truck_mode %>
  </div>

  <div class="field">
    <%= form.label :judge %>
    <%= form.text_field :judge %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time %>
  </div>

  <div class="field">
    <%= form.label :speed %>
    <%= form.text_field :speed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing Track</h1>

<%= render 'form', track: @track %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tracks</h1>

<table>
  <thead>
    <tr>
      <th>Truck mode</th>
      <th>Judge</th>
      <th>Time</th>
      <th>Speed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= track.truck_mode %></td>
        <td><%= track.judge %></td>
        <td><%= track.time %></td>
        <td><%= track.speed %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Edit', edit_track_path(track) %></td>
        <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Track', new_track_path %>
<%= link_to "Home", root_path %>

app/views/tracks/new.html.erb
<h1>New Track</h1>

<%= render 'form', track: @track %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Truck mode:</strong>
  <%= @track.truck_mode %>
</p>

<p>
  <strong>Judge:</strong>
  <%= @track.judge %>
</p>

<p>
  <strong>Time:</strong>
  <%= @track.time %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @track.speed %>
</p>

<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>